---
- name: Install MySQL on Linux
  hosts: all
  become: yes
  tasks:

    - name: Install MySQL (Debian-based)
      apt:
        name: mysql-server
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start MySQL/MariaDB Service
      service:
        name: "{{ 'mysql' if ansible_os_family == 'Debian' else 'mariadb' }}"
        state: started
        enabled: yes
