---
- name: Install VLC on Windows Server
  hosts: all
  gather_facts: true
  tasks:

    - name: Set Downloads folder path
      set_fact:
        downloads_path: "C:\\"

    - name: Download VLC Installer
      win_get_url:
        url: "https://get.videolan.org/vlc/3.0.20/win64/vlc-3.0.20-win64.exe"
        dest: "{{ downloads_path }}\\vlc_installer.exe"

    - name: Install VLC
      win_command: "vlc_installer.exe /S"
      args:
        chdir: "{{ downloads_path }}"

    - name: Verify VLC Installation
      win_stat:
        path: "C:\\Program Files\\VideoLAN\\VLC\\vlc.exe"
      register: vlc_installed

    - name: Display Installation Status
      debug:
        msg: "VLC installation was successful!"
      when: vlc_installed.stat.exists
